### PR TITLE
Restructure software

### PR DESCRIPTION
**Pull request by plata**
use: src, test, examples directories

see #12 

Disclaimer: I could not test the build locally (the Travis checks are fine though).

### CODE REVIEW

**Comment by plata** [comment]
I'm not really sure if this structure is 100% compatible with xmlpg.

**Comment by leif81** [comment]
Thanks @plata !

I'm not too concerned if it breaks xmlpg. There was a time when we regenerated the code frequently, but at this point it's used more to generate the sources one and then never look back.

**Comment by plata** [comment]
I see.

If I may suggest something: Use squash merging to keep the commits on master more precise.

**Comment by plata** [comment]
In case you are interested: I was referring especially to https://github.com/open-dis/xmlpg/issues/14.

**Pull request merged**
