### PR TITLE
Use CMake build system + build RPM

### LINKED ISSUE #14: Build packages (e.g. RPM/DEB)
There should be 3 packages:
- utils
- dis6 (requires utils)
- dis7 (requires utils)

I'm not sure if/how this is possible with premake. An alternative would be CMake (CPack).

These packages could then also be released via GitHub releases.

### LINKED ISSUE #17: Rework PDUBank handling
Currently, the PDUBank (and thus the available PDUs) is hardcoded in https://github.com/open-dis/open-dis-cpp/blob/05aa32c59397b7c889a6b603a6327c69ae0b4420/src/utils/IncomingMessage.cpp#L46

As a consequence, it is not possible to use a different PDUBank without changing the code. However, this is required e.g. to use DIS 7 PDUs.

I suggest to implement the PDUBank handling in a similar way to the PacketProcessors, i.e.
- make a PDUBank base class with a method `Pdu* GetStaticPDU(const DataStream&) const`
- register the desired PDUBank implementation similar to `IncomingMessage::AddProcessor`

This would also help reducing the cyclic dependencies between the PDUs and the utils.

### PR DESCRIPTION
**Pull request by phoppermann**
To use it in your CMake project:
```CMake
find_package(OpenDis REQUIRED)
```

Currently only RPM packages are built. However, it is easy to add other packaging methods like archive, deb etc.

fixes #14

### CODE REVIEW

**Comment by phoppermann** [comment]
**Note:**
- The examples and tests are not built with CMake. If you consider switching to CMake completely, they should be integrated in the CMake build after merging this.
- Travis should be updated to build with CMake (see https://docs.travis-ci.com/user/languages/cpp/).

**Comment by leif81** [comment]
Thank-you @phoppermann 

Could you explain how to invoke the build to generate the rpm? I'm pretty new to cmake.

**Comment by phoppermann** [comment]
You simply call
```
make package
```
So the complete process would be:
```
git clone https://github.com/open-dis/open-dis-cpp.git
mkdir open-dis-cpp-build
cd open-dis-cpp-build
cmake ../open-dis-cpp
make -j package
```

**Comment by phoppermann** [comment]
@CarlosSprekelsen this is more of a general issue. Like also described in #18, I don't currently see how PDUs of different DIS versions can be used in parallel properly.

As long as you include open-dis-cpp in your project via CMake `find_package`, you do not have to worry about include paths (CMake will handle this for you). So no changes in the cpp required.

If you do not use CMake, you have to set your include paths accordingly.

**Comment by leif81** [comment]
Thank-you for your contribution @phoppermann . I'm going to close as a duplicate of #37 which was just merged in.

**Pull request closed without merging**
