### PR TITLE
CMake for OpenDIS C++

### PR DESCRIPTION
**Pull request by tm132**
Created CMake files to build C++ OpenDIS 6, OpenDIS 7 (currently commented out due to build errors), and the example apps based on SCRIMMAGE's (https://github.com/gtri/scrimmage) CMake build structure.  Requires CMake 3.5 or newer. My system is running Ubuntu 18.04.3 LTS, CMake 3.10.2, CCache 3.4.1, GNU C/C++ compiler 7.4.0, libSDL2 2.0.8, libSDL2main 2.0.8, libSDL2_net 2.0.1.

Feel free to merge these changes or not, according to your preference. This should not affect any of the code or build system currently in place for OpenDIS C++.

Usage, in main project directory:
```
mkdir build/
cd build/
cmake ..
make
```
`make clean` and `sudo make install` also available. `sudo make install` will deploy the DIS libraries and h files to proper system locations. The full list of targets is in the main Makefile (when generated) at the bottom of the file.

### CODE REVIEW

**Comment by leif81** [comment]
Thank-you @tm132 

Adding CMake probably makes a lot of sense. The main reason we'd been using Premake was it did a good job at generating both Makefiles for Linux and Visual Studio project files for Windows. Do you happen to have any experience using CMake with Visual Studio? If it works well then switching the whole build system over to CMake probably makes sense.

**Comment by leif81** [comment]
I've got to admit though, as a CMake newbie, the CMake build files here are very verbose compared to the equivalent `premake.lua` build file for compling Open DIS. Is CMake typically this verbose? That does concerns me from a maintenance perspective.  I'm interested to hear your thoughts on it.

**Comment by tm132** [comment]
To be honest, I'm new to CMake too, and I was using this project as an opportunity to familiarize myself with it. So I can't really answer your question about using it for with Windows/Visual Studio. I have only built this code with cmake in Ubuntu. Theoretically, given what's in the CMake files, MacOS should work with these files too, but it hasn't been tested. There is probably no Windows support in these files since SCRIMMAGE does not run in a Windows environment.

As to the complexity, I agree, the Lua is much easier to read and understand. The Lua made it very simple to know what needed to be put in the `examples/CMakeLists.txt` file which I had to write almost completely from scratch, since SCRIMMAGE didn't have anything like that. From what I've been told by others more proficient than myself with CMake about CMake: It's annoying to set up, but once you get it in place, you rarely have to change it. Usually only if you add 3rd party libraries to the project, in which case you'd add a file in `cmake/modules/` to find it and then reference it in the main `CMakeLists.txt` file. The SDL2 ones are a example of this, albeit more complicated than most files like this. This is a more straightforward example: https://github.com/tm132/scrimmage/blob/master/cmake/Modules/FindGeographicLib.cmake

Anyway, merging this shouldn't break anything in the OpenDIS project, but it's fine with me if you decide not to merge it in. We appreciate the work you've done to develop these libraries so we don't have to write this part of it. Also your tutorials/writeups were very insightful. :)

**Comment by leif81** [comment]
Thankyou for the detailed response @tm132 . I'm going to put some more thought into it before merging. There is some more discussion happening about CMake in #36 in case you aren't following along there yet.

**Comment by leif81** [comment]
Thank-you for your contribution @tm132 . CMake is obviously a popular request. We received three different pull requests for this. #37 was just merged in. I'll close this one.

**Pull request closed without merging**
